### ISSUE TITLE
Implement detailed geometry for SAND ECAL endcaps

### ISSUE THREAD

**Issue by GianfrancoIngratta** [DUNE/duneggd#10]
The current  SAND ECAL endcaps are approximated with 2 disks with a radius equal to the SAND radius. It is necessary to implement a more realistic geometry that reproduces the internal endcaps structure. Here in the fig below a section of the geometry to be implemented:
![image](https://github.com/DUNE/duneggd/assets/48324147/d0da3b24-8ca8-47fd-8f16-6c74d0f0d4c9)

**Comment by ast0815** [comment]
I think this should go into the [dunendggd](https://github.com/DUNE/dunendggd) (note the additional "nd") repository, and not in this one. This one here is for the far detector geometry. Please open an issue there and close this one.
